management:
  server:
    port: 8081           # ìš´ì˜ íŠ¸ë˜í”½ê³¼ ë¶„ë¦¬ ê¶Œì¥
    address: 0.0.0.0     # ğŸ”´ ì¤‘ìš”: ì»¨í…Œì´ë„ˆì—ì„œ ì ‘ê·¼ ê°€ëŠ¥í•˜ê²Œ ì „ì²´ ë°”ì¸ë”©
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:                # ê³µí†µ ë¼ë²¨(ì„œë¹„ìŠ¤ëª…/í™˜ê²½/ì§€ì—­ ë“±)ë¡œ ì§‘ê³„/í•„í„°ì— ìœ ìš©
      application: channeling-be
#      env: dev
#      region: ap-northeast-2 # ë©€í‹°ë¦¬ì „ ì ìš© ì‹œ ìœ ìš©í•˜ë‹¤ê³  í•œë‹¤
